In [3]:
import pandas as pd

In [4]:
res_df = pd.read_csv('best_res_df.csv')

In [5]:
res_b4_training = pd.read_csv('evals_before_training.csv')

In [6]:
res_df

,folder_name,filename,step,dataset,lr,tokens,disp_type,disp_value,tau_cosine,tau_l2,...,"piqa,acc_norm,none","arc_easy,acc_norm,none","arc_challenge,acc_norm,none","mmlu,acc,none","medmcqa,acc_norm,none","agieval_en,acc,none","squadv2,exact,none",mean_metric,disp,mean_metric_increasing
0,midtrain_gpt2_Salesforce-wikitext_lr-1e-05_tok...,lm_eval_end_1102.json,1102,Salesforce-wikitext,0.00001,300000000.0,NaN,1.0,NaN,NaN,...,0.60,0.35,0.22,0.256491,0.24,0.241,0.47,0.364157,None-1,0.352649
1,midtrain_gpt2_Salesforce-wikitext_lr-1e-05_tok...,lm_eval_end_1102.json,1102,Salesforce-wikitext,0.00001,300000000.0,covariance,0.5,NaN,NaN,...,0.62,0.36,0.22,0.255263,0.25,0.237,0.38,0.370984,covariance-0.5,0.369526
2,midtrain_gpt2_Salesforce-wikitext_lr-1e-05_tok...,lm_eval_end_1102.json,1102,Salesforce-wikitext,0.00001,300000000.0,hinge,1.0,NaN,NaN,...,0.62,0.36,0.21,0.255614,0.24,0.238,0.47,0.372495,hinge-1.0,0.370561
3,midtrain_gpt2_Salesforce-wikitext_infonce_cosi...,lm_eval_end_1102.json,1102,Salesforce-wikitext,0.00001,300000000.0,infonce_cosine,1.0,0.5,NaN,...,0.61,0.35,0.22,0.256667,0.27,0.239,0.47,0.368470,infonce_cosine-1.0,0.362667
4,midtrain_gpt2_Salesforce-wikitext_lr-1e-05_tok...,lm_eval_end_1102.json,1102,Salesforce-wikitext,0.00001,300000000.0,infonce_l2,0.5,NaN,0.5,...,0.60,0.37,0.25,0.248947,0.27,0.232,0.18,0.348712,infonce_l2-0.5,0.361895

In [7]:
res_b4_training

,model,"anli_r1,acc,none","anli_r2,acc,none","anli_r3,acc,none","hellaswag,acc_norm,none","lambada_standard,acc,none","lambada_openai,acc,none","openbookqa,acc_norm,none","paloma_wikitext_103,word_perplexity,none","truthfulqa_mc2,acc,none",...,"squad_completion,contains,none","boolq,acc,none","piqa,acc_norm,none","arc_easy,acc_norm,none","arc_challenge,acc_norm,none","mmlu,acc,none","medmcqa,acc_norm,none","agieval_en,acc,none","squadv2,exact,none",mean_metric
0,gpt2,0.40,0.37,0.42,0.42,0.27,0.34,0.27,52.286709,0.452888,...,0.39,0.45,0.58,0.37,0.22,0.252281,0.23,0.232,0.17,0.351509
1,gpt2-medium,0.37,0.38,0.39,0.46,0.34,0.39,0.30,35.607770,0.412553,...,0.45,0.75,0.72,0.41,0.28,0.246491,0.26,0.216,0.07,0.388058
2,gpt2-large,0.41,0.39,0.41,0.52,0.32,0.43,0.28,29.606493,0.418631,...,0.50,0.70,0.73,0.48,0.22,0.264035,0.27,0.228,0.15,0.408370
3,gpt2-xl,0.36,0.38,0.20,0.52,0.38,0.46,0.29,26.494969,0.378899,...,0.53,0.61,0.75,0.51,0.31,0.254561,0.35,0.229,0.17,0.405137

In [10]:
config_cols = ['folder_name', 'filename', 'step', 'dataset', 'lr', 'tokens', 'disp_type', 'disp_value', 
               'tau_cosine', 'tau_l2', 'fewshot', 'maxsample', 'seed', 'suffix', 'config_hash', 'gradient_clip', 'disp']
metric_cols = [col for col in res_df.columns if col not in config_cols]
metric_no_ppl = [c for c in metric_cols if c != 'paloma_wikitext_103,word_perplexity,none']
increasing_metrics = [
    "anli_r2",
    "hellaswag",
    "lambada_openai",
    "lambada_standard",
    "winogrande",
    "squad_completion",
    "piqa",
    "arc_easy",
    "mmlu",
    "medmcqa",
] # ones where larger models increase performance.
increasing_metrics_names = [
    i for i in metric_no_ppl if any(metric in i for metric in increasing_metrics)
]
# Assert that all increasing_metrics are included
for metric in increasing_metrics:
    assert any(metric in name for name in increasing_metrics_names), f"Metric '{metric}' not found in metric_no_ppl"
# Create heatmap

In [11]:
res_df[increasing_metrics_names]

,"anli_r2,acc,none","hellaswag,acc_norm,none","lambada_standard,acc,none","lambada_openai,acc,none","winogrande,acc,none","squad_completion,contains,none","piqa,acc_norm,none","arc_easy,acc_norm,none","mmlu,acc,none","medmcqa,acc_norm,none"
0,0.39,0.42,0.23,0.35,0.50,0.19,0.60,0.35,0.256491,0.24
1,0.40,0.42,0.24,0.34,0.54,0.27,0.62,0.36,0.255263,0.25
2,0.40,0.42,0.23,0.37,0.57,0.24,0.62,0.36,0.255614,0.24
3,0.40,0.42,0.24,0.33,0.53,0.22,0.61,0.35,0.256667,0.27
4,0.41,0.42,0.27,0.35,0.55,0.13,0.60,0.37,0.248947,0.27

In [12]:
res_b4_training[increasing_metrics_names]

,"anli_r2,acc,none","hellaswag,acc_norm,none","lambada_standard,acc,none","lambada_openai,acc,none","winogrande,acc,none","squad_completion,contains,none","piqa,acc_norm,none","arc_easy,acc_norm,none","mmlu,acc,none","medmcqa,acc_norm,none"
0,0.37,0.42,0.27,0.34,0.49,0.39,0.58,0.37,0.252281,0.23
1,0.38,0.46,0.34,0.39,0.54,0.45,0.72,0.41,0.246491,0.26
2,0.39,0.52,0.32,0.43,0.63,0.50,0.73,0.48,0.264035,0.27
3,0.38,0.52,0.38,0.46,0.61,0.53,0.75,0.51,0.254561,0.35

In [13]:
def render_latex_table_simple(sorted_df, increasing_metrics, res_b4_training, 
                               metric_name_map=None, model_name='gpt2', 
                               decimals=1, decimals_average=2, output_path=None):
    """
    Generate LaTeX table from sorted_df showing improvements over baseline.
    
    Args:
        sorted_df: DataFrame with rows sorted by performance
        increasing_metrics: List of metric column names to include (where higher is better)
        res_b4_training: DataFrame with initial (before training) baseline values for all model sizes
        metric_name_map: Dict mapping metric column names to short names (e.g., {'anli_r2,acc,none': 'ANLI-R2'})
        model_name: Name of the model being trained (e.g., 'gpt2') - used to determine baseline
        decimals: Number of decimal places for metric values
        decimals_average: Number of decimal places for average column
        output_path: Path to save the .tex file (default: ./tables/results_table.tex)
    """
    import os
    import numpy as np
    import pandas as pd
    
    # Build rows list
    rows = []
    
    # Rows 1-4: All pretrained models (no mid-training) - from res_b4_training
    for _, model_row in res_b4_training.iterrows():
        model = model_row['model']
        rows.append({
            "method": f"Pretrained ({model})",
            "src": "initial",
            "data": model_row
        })
    
    # Get baseline reference (the specific model being trained)
    baseline_reference = res_b4_training[res_b4_training['model'] == model_name].iloc[0]
    
    # Row 5: Default loss (None-1 baseline best)
    baseline_row = sorted_df[sorted_df['disp'] == 'None-1'].iloc[0]
    rows.append({
        "method": "Default loss",
        "src": "baseline_best",
        "data": baseline_row
    })
    
    # Remaining rows: dispersion methods (excluding None-1)
    for _, row in sorted_df[sorted_df['disp'] != 'None-1'].iterrows():
        method = row['disp_type'] if pd.notna(row['disp_type']) else "None"
        rows.append({
            "method": method,
            "src": "run",
            "data": row
        })
    
    # Build table header - use metric_name_map if provided
    if metric_name_map is None:
        header_names = [m.split(',')[0].replace('_', r'\_') for m in increasing_metrics]
    else:
        header_names = [metric_name_map.get(m, m.split(',')[0]).replace('_', r'\_') 
                        for m in increasing_metrics]
    header_names.append("Average")
    
    column_alignment = "l " + " ".join(["c"] * len(header_names))
    
    lines = []
    lines.append(r"\begin{tabular}{" + column_alignment + r"}")
    lines.append(r"\toprule")
    lines.append("Method & " + " & ".join(header_names) + r" \\")
    lines.append(r"\midrule")
    
    # Process each row
    for row_info in rows:
        # Escape underscores in method name
        method_escaped = row_info['method'].replace('_', r'\_')
        metric_cells = []
        values_for_average = []
        baseline_values_for_average = []
        
        for metric_name in increasing_metrics:
            # Get value and baseline
            value = row_info['data'][metric_name]
            baseline_value = baseline_reference[metric_name]
            
            if not np.isfinite(value):
                metric_cells.append("N/A")
                continue
            
            cell_text = f"{value:.{decimals}f}"
            
            # Add colored difference (except for initial rows)
            if row_info['src'] != "initial" and np.isfinite(baseline_value):
                difference = np.round(value, decimals) - np.round(baseline_value, decimals)
                sign = "+" if difference >= 0 else ""
                color_name = "forestgreen" if difference >= 0 else "crimson"
                cell_text += f"$_{{\\textcolor{{{color_name}}}{{({sign}{difference:.{decimals}f})}}}}$"
            
            metric_cells.append(cell_text)
            if np.isfinite(value):
                values_for_average.append(value)
            if np.isfinite(baseline_value):
                baseline_values_for_average.append(baseline_value)
        
        # Calculate average
        if values_for_average:
            average_value = float(np.mean(values_for_average))
            average_baseline = float(np.mean(baseline_values_for_average)) if baseline_values_for_average else np.nan
            
            if row_info['src'] == "initial" or not np.isfinite(average_baseline):
                average_cell_text = f"{average_value:.{decimals_average}f}"
            else:
                difference = np.round(average_value, decimals_average) - np.round(average_baseline, decimals_average)
                sign = "+" if difference >= 0 else ""
                color_name = "forestgreen" if difference >= 0 else "crimson"
                average_cell_text = f"{average_value:.{decimals_average}f}$_{{\\textcolor{{{color_name}}}{{({sign}{difference:.{decimals_average}f})}}}}$"
        else:
            average_cell_text = "N/A"
        
        metric_cells.append(average_cell_text)
        lines.append(method_escaped + " & " + " & ".join(metric_cells) + r" \\")
    
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    
    # Save and print
    table_tex = "\n".join(lines)
    if output_path is None:
        os.makedirs("./tables", exist_ok=True)
        output_path = "./tables/results_table.tex"
    
    with open(output_path, "w") as f:
        f.write(table_tex)
    
    print("\n===== LaTeX table =====\n")
    print(table_tex)
    print(f"\n[Saved to: {output_path}]\n")
    
    return table_tex

In [14]:
increasing_metrics_names

['anli_r2,acc,none',
 'hellaswag,acc_norm,none',
 'lambada_standard,acc,none',
 'lambada_openai,acc,none',
 'winogrande,acc,none',
 'squad_completion,contains,none',
 'piqa,acc_norm,none',
 'arc_easy,acc_norm,none',
 'mmlu,acc,none',
 'medmcqa,acc_norm,none']

In [15]:
metric_names = {
    'anli_r2,acc,none': 'ANLI-R2',
 'hellaswag,acc_norm,none': 'HS',
 'lambada_standard,acc,none': 'LAMBADA-S',
 'lambada_openai,acc,none': 'LAMBADA-O',
 'winogrande,acc,none': 'WG',
 'squad_completion,contains,none': 'SQUAD-C',
 'piqa,acc_norm,none': 'PIQA',
 'arc_easy,acc_norm,none': 'ARC-E',
 'mmlu,acc,none': 'MMLU',
 'medmcqa,acc_norm,none': 'MEDMCQA',
}

In [24]:
res_df_100t = res_df.copy()
res_df_100t[increasing_metrics_names] = res_df_100t[increasing_metrics_names] * 100
res_b4_training_100t = res_b4_training.copy()
res_b4_training_100t[increasing_metrics_names] = res_b4_training_100t[increasing_metrics_names] * 100
render_latex_table_simple(
    sorted_df=res_df_100t,
    increasing_metrics=increasing_metrics_names,
    res_b4_training=res_b4_training_100t,
    metric_name_map=metric_names,  # Pass the mapping
    model_name='gpt2',  # Which model is being trained
    decimals=1,
    decimals_average=2,
    output_path='./results_table.tex'
)

===== LaTeX table =====

\begin{tabular}{l c c c c c c c c c c c}
\toprule
Method & ANLI-R2 & HS & LAMBADA-S & LAMBADA-O & WG & SQUAD-C & PIQA & ARC-E & MMLU & MEDMCQA & Average \\
\midrule
Pretrained (gpt2) & 37.0 & 42.0 & 27.0 & 34.0 & 49.0 & 39.0 & 58.0 & 37.0 & 25.2 & 23.0 & 37.12 \\
Pretrained (gpt2-medium) & 38.0 & 46.0 & 34.0 & 39.0 & 54.0 & 45.0 & 72.0 & 41.0 & 24.6 & 26.0 & 41.96 \\
Pretrained (gpt2-large) & 39.0 & 52.0 & 32.0 & 43.0 & 63.0 & 50.0 & 73.0 & 48.0 & 26.4 & 27.0 & 45.34 \\
Pretrained (gpt2-xl) & 38.0 & 52.0 & 38.0 & 46.0 & 61.0 & 53.0 & 75.0 & 51.0 & 25.5 & 35.0 & 47.45 \\
Default loss & 39.0$_{\textcolor{forestgreen}{(+2.0)}}$ & 42.0$_{\textcolor{forestgreen}{(+0.0)}}$ & 23.0$_{\textcolor{crimson}{(-4.0)}}$ & 35.0$_{\textcolor{forestgreen}{(+1.0)}}$ & 50.0$_{\textcolor{forestgreen}{(+1.0)}}$ & 19.0$_{\textcolor{crimson}{(-20.0)}}$ & 60.0$_{\textcolor{forestgreen}{(+2.0)}}$ & 35.0$_{\textcolor{crimson}{(-2.0)}}$ & 25.6$_{\textcolor{forestgreen}{(+0.4)}}$ & 24.0$_{\textcolor{forestgreen}{(+1.0)}}$ & 35.26$_{\textcolor{crimson}{(-1.86)}}$ \\
covariance & 40.0$_{\textcolor{forestgreen}{(+3.0)}}$ & 42.0$_{\textcolor{forestgreen}{(+0.0)}}$ & 24.0$_{\textcolor{crimson}{(-3.0)}}$ & 34.0$_{\textcolor{forestgreen}{(+0.0)}}$ & 54.0$_{\textcolor{forestgreen}{(+5.0)}}$ & 27.0$_{\textcolor{crimson}{(-12.0)}}$ & 62.0$_{\textcolor{forestgreen}{(+4.0)}}$ & 36.0$_{\textcolor{crimson}{(-1.0)}}$ & 25.5$_{\textcolor{forestgreen}{(+0.3)}}$ & 25.0$_{\textcolor{forestgreen}{(+2.0)}}$ & 36.95$_{\textcolor{crimson}{(-0.17)}}$ \\
hinge & 40.0$_{\textcolor{forestgreen}{(+3.0)}}$ & 42.0$_{\textcolor{forestgreen}{(+0.0)}}$ & 23.0$_{\textcolor{crimson}{(-4.0)}}$ & 37.0$_{\textcolor{forestgreen}{(+3.0)}}$ & 57.0$_{\textcolor{forestgreen}{(+8.0)}}$ & 24.0$_{\textcolor{crimson}{(-15.0)}}$ & 62.0$_{\textcolor{forestgreen}{(+4.0)}}$ & 36.0$_{\textcolor{crimson}{(-1.0)}}$ & 25.6$_{\textcolor{forestgreen}{(+0.4)}}$ & 24.0$_{\textcolor{forestgreen}{(+1.0)}}$ & 37.06$_{\textcolor{crimson}{(-0.06)}}$ \\
infonce\_cosine & 40.0$_{\textcolor{forestgreen}{(+3.0)}}$ & 42.0$_{\textcolor{forestgreen}{(+0.0)}}$ & 24.0$_{\textcolor{crimson}{(-3.0)}}$ & 33.0$_{\textcolor{crimson}{(-1.0)}}$ & 53.0$_{\textcolor{forestgreen}{(+4.0)}}$ & 22.0$_{\textcolor{crimson}{(-17.0)}}$ & 61.0$_{\textcolor{forestgreen}{(+3.0)}}$ & 35.0$_{\textcolor{crimson}{(-2.0)}}$ & 25.7$_{\textcolor{forestgreen}{(+0.5)}}$ & 27.0$_{\textcolor{forestgreen}{(+4.0)}}$ & 36.27$_{\textcolor{crimson}{(-0.85)}}$ \\
infonce\_l2 & 41.0$_{\textcolor{forestgreen}{(+4.0)}}$ & 42.0$_{\textcolor{forestgreen}{(+0.0)}}$ & 27.0$_{\textcolor{forestgreen}{(+0.0)}}$ & 35.0$_{\textcolor{forestgreen}{(+1.0)}}$ & 55.0$_{\textcolor{forestgreen}{(+6.0)}}$ & 13.0$_{\textcolor{crimson}{(-26.0)}}$ & 60.0$_{\textcolor{forestgreen}{(+2.0)}}$ & 37.0$_{\textcolor{forestgreen}{(+0.0)}}$ & 24.9$_{\textcolor{crimson}{(-0.3)}}$ & 27.0$_{\textcolor{forestgreen}{(+4.0)}}$ & 36.19$_{\textcolor{crimson}{(-0.93)}}$ \\
\bottomrule
\end{tabular}

[Saved to: ./results_table.tex]

'\\begin{tabular}{l c c c c c c c c c c c}\n\\toprule\nMethod & ANLI-R2 & HS & LAMBADA-S & LAMBADA-O & WG & SQUAD-C & PIQA & ARC-E & MMLU & MEDMCQA & Average \\\\\n\\midrule\nPretrained (gpt2) & 37.0 & 42.0 & 27.0 & 34.0 & 49.0 & 39.0 & 58.0 & 37.0 & 25.2 & 23.0 & 37.12 \\\\\nPretrained (gpt2-medium) & 38.0 & 46.0 & 34.0 & 39.0 & 54.0 & 45.0 & 72.0 & 41.0 & 24.6 & 26.0 & 41.96 \\\\\nPretrained (gpt2-large) & 39.0 & 52.0 & 32.0 & 43.0 & 63.0 & 50.0 & 73.0 & 48.0 & 26.4 & 27.0 & 45.34 \\\\\nPretrained (gpt2-xl) & 38.0 & 52.0 & 38.0 & 46.0 & 61.0 & 53.0 & 75.0 & 51.0 & 25.5 & 35.0 & 47.45 \\\\\nDefault loss & 39.0$_{\\textcolor{forestgreen}{(+2.0)}}$ & 42.0$_{\\textcolor{forestgreen}{(+0.0)}}$ & 23.0$_{\\textcolor{crimson}{(-4.0)}}$ & 35.0$_{\\textcolor{forestgreen}{(+1.0)}}$ & 50.0$_{\\textcolor{forestgreen}{(+1.0)}}$ & 19.0$_{\\textcolor{crimson}{(-20.0)}}$ & 60.0$_{\\textcolor{forestgreen}{(+2.0)}}$ & 35.0$_{\\textcolor{crimson}{(-2.0)}}$ & 25.6$_{\\textcolor{forestgreen}{(+0.4)}}$ & 24.0$_{\\textcolor{forestgreen}{(+1.0)}}$ & 35.26$_{\\textcolor{crimson}{(-1.86)}}$ \\\\\ncovariance & 40.0$_{\\textcolor{forestgreen}{(+3.0)}}$ & 42.0$_{\\textcolor{forestgreen}{(+0.0)}}$ & 24.0$_{\\textcolor{crimson}{(-3.0)}}$ & 34.0$_{\\textcolor{forestgreen}{(+0.0)}}$ & 54.0$_{\\textcolor{forestgreen}{(+5.0)}}$ & 27.0$_{\\textcolor{crimson}{(-12.0)}}$ & 62.0$_{\\textcolor{forestgreen}{(+4.0)}}$ & 36.0$_{\\textcolor{crimson}{(-1.0)}}$ & 25.5$_{\\textcolor{forestgreen}{(+0.3)}}$ & 25.0$_{\\textcolor{forestgreen}{(+2.0)}}$ & 36.95$_{\\textcolor{crimson}{(-0.17)}}$ \\\\\nhinge & 40.0$_{\\textcolor{forestgreen}{(+3.0)}}$ & 42.0$_{\\textcolor{forestgreen}{(+0.0)}}$ & 23.0$_{\\textcolor{crimson}{(-4.0)}}$ & 37.0$_{\\textcolor{forestgreen}{(+3.0)}}$ & 57.0$_{\\textcolor{forestgreen}{(+8.0)}}$ & 24.0$_{\\textcolor{crimson}{(-15.0)}}$ & 62.0$_{\\textcolor{forestgreen}{(+4.0)}}$ & 36.0$_{\\textcolor{crimson}{(-1.0)}}$ & 25.6$_{\\textcolor{forestgreen}{(+0.4)}}$ & 24.0$_{\\textcolor{forestgreen}{(+1.0)}}$ & 37.06$_{\\textcolor{crimson}{(-0.06)}}$ \\\\\ninfonce\\_cosine & 40.0$_{\\textcolor{forestgreen}{(+3.0)}}$ & 42.0$_{\\textcolor{forestgreen}{(+0.0)}}$ & 24.0$_{\\textcolor{crimson}{(-3.0)}}$ & 33.0$_{\\textcolor{crimson}{(-1.0)}}$ & 53.0$_{\\textcolor{forestgreen}{(+4.0)}}$ & 22.0$_{\\textcolor{crimson}{(-17.0)}}$ & 61.0$_{\\textcolor{forestgreen}{(+3.0)}}$ & 35.0$_{\\textcolor{crimson}{(-2.0)}}$ & 25.7$_{\\textcolor{forestgreen}{(+0.5)}}$ & 27.0$_{\\textcolor{forestgreen}{(+4.0)}}$ & 36.27$_{\\textcolor{crimson}{(-0.85)}}$ \\\\\ninfonce\\_l2 & 41.0$_{\\textcolor{forestgreen}{(+4.0)}}$ & 42.0$_{\\textcolor{forestgreen}{(+0.0)}}$ & 27.0$_{\\textcolor{forestgreen}{(+0.0)}}$ & 35.0$_{\\textcolor{forestgreen}{(+1.0)}}$ & 55.0$_{\\textcolor{forestgreen}{(+6.0)}}$ & 13.0$_{\\textcolor{crimson}{(-26.0)}}$ & 60.0$_{\\textcolor{forestgreen}{(+2.0)}}$ & 37.0$_{\\textcolor{forestgreen}{(+0.0)}}$ & 24.9$_{\\textcolor{crimson}{(-0.3)}}$ & 27.0$_{\\textcolor{forestgreen}{(+4.0)}}$ & 36.19$_{\\textcolor{crimson}{(-0.93)}}$ \\\\\n\\bottomrule\n\\end{tabular}'

NameError: name 'df' is not defined

In [27]:
res_df_100t = res_df.copy()
res_df_100t[increasing_metrics_names] = res_df_100t[increasing_metrics_names] * 100
res_b4_training_100t = res_b4_training.copy()
res_b4_training_100t[increasing_metrics_names] = res_b4_training_100t[increasing_metrics_names] * 100
render_latex_table_simple(
    sorted_df=res_df_100t,
    increasing_metrics=[n for n in metric_names if n  not in ['squad_completion,contains,none', 'lambada_standard,acc,none', 'arc_easy,acc_norm,none']],
    res_b4_training=res_b4_training_100t,
    metric_name_map=metric_names,  # Pass the mapping
    model_name='gpt2',  # Which model is being trained
    decimals=1,
    decimals_average=2,
    output_path='./results_table.tex'
)

===== LaTeX table =====

\begin{tabular}{l c c c c c c c c}
\toprule
Method & ANLI-R2 & HS & LAMBADA-O & WG & PIQA & MMLU & MEDMCQA & Average \\
\midrule
Pretrained (gpt2) & 37.0 & 42.0 & 34.0 & 49.0 & 58.0 & 25.2 & 23.0 & 38.32 \\
Pretrained (gpt2-medium) & 38.0 & 46.0 & 39.0 & 54.0 & 72.0 & 24.6 & 26.0 & 42.81 \\
Pretrained (gpt2-large) & 39.0 & 52.0 & 43.0 & 63.0 & 73.0 & 26.4 & 27.0 & 46.20 \\
Pretrained (gpt2-xl) & 38.0 & 52.0 & 46.0 & 61.0 & 75.0 & 25.5 & 35.0 & 47.49 \\
Default loss & 39.0$_{\textcolor{forestgreen}{(+2.0)}}$ & 42.0$_{\textcolor{forestgreen}{(+0.0)}}$ & 35.0$_{\textcolor{forestgreen}{(+1.0)}}$ & 50.0$_{\textcolor{forestgreen}{(+1.0)}}$ & 60.0$_{\textcolor{forestgreen}{(+2.0)}}$ & 25.6$_{\textcolor{forestgreen}{(+0.4)}}$ & 24.0$_{\textcolor{forestgreen}{(+1.0)}}$ & 39.38$_{\textcolor{forestgreen}{(+1.06)}}$ \\
covariance & 40.0$_{\textcolor{forestgreen}{(+3.0)}}$ & 42.0$_{\textcolor{forestgreen}{(+0.0)}}$ & 34.0$_{\textcolor{forestgreen}{(+0.0)}}$ & 54.0$_{\textcolor{forestgreen}{(+5.0)}}$ & 62.0$_{\textcolor{forestgreen}{(+4.0)}}$ & 25.5$_{\textcolor{forestgreen}{(+0.3)}}$ & 25.0$_{\textcolor{forestgreen}{(+2.0)}}$ & 40.36$_{\textcolor{forestgreen}{(+2.04)}}$ \\
hinge & 40.0$_{\textcolor{forestgreen}{(+3.0)}}$ & 42.0$_{\textcolor{forestgreen}{(+0.0)}}$ & 37.0$_{\textcolor{forestgreen}{(+3.0)}}$ & 57.0$_{\textcolor{forestgreen}{(+8.0)}}$ & 62.0$_{\textcolor{forestgreen}{(+4.0)}}$ & 25.6$_{\textcolor{forestgreen}{(+0.4)}}$ & 24.0$_{\textcolor{forestgreen}{(+1.0)}}$ & 41.08$_{\textcolor{forestgreen}{(+2.76)}}$ \\
infonce\_cosine & 40.0$_{\textcolor{forestgreen}{(+3.0)}}$ & 42.0$_{\textcolor{forestgreen}{(+0.0)}}$ & 33.0$_{\textcolor{crimson}{(-1.0)}}$ & 53.0$_{\textcolor{forestgreen}{(+4.0)}}$ & 61.0$_{\textcolor{forestgreen}{(+3.0)}}$ & 25.7$_{\textcolor{forestgreen}{(+0.5)}}$ & 27.0$_{\textcolor{forestgreen}{(+4.0)}}$ & 40.24$_{\textcolor{forestgreen}{(+1.92)}}$ \\
infonce\_l2 & 41.0$_{\textcolor{forestgreen}{(+4.0)}}$ & 42.0$_{\textcolor{forestgreen}{(+0.0)}}$ & 35.0$_{\textcolor{forestgreen}{(+1.0)}}$ & 55.0$_{\textcolor{forestgreen}{(+6.0)}}$ & 60.0$_{\textcolor{forestgreen}{(+2.0)}}$ & 24.9$_{\textcolor{crimson}{(-0.3)}}$ & 27.0$_{\textcolor{forestgreen}{(+4.0)}}$ & 40.70$_{\textcolor{forestgreen}{(+2.38)}}$ \\
\bottomrule
\end{tabular}

[Saved to: ./results_table.tex]

'\\begin{tabular}{l c c c c c c c c}\n\\toprule\nMethod & ANLI-R2 & HS & LAMBADA-O & WG & PIQA & MMLU & MEDMCQA & Average \\\\\n\\midrule\nPretrained (gpt2) & 37.0 & 42.0 & 34.0 & 49.0 & 58.0 & 25.2 & 23.0 & 38.32 \\\\\nPretrained (gpt2-medium) & 38.0 & 46.0 & 39.0 & 54.0 & 72.0 & 24.6 & 26.0 & 42.81 \\\\\nPretrained (gpt2-large) & 39.0 & 52.0 & 43.0 & 63.0 & 73.0 & 26.4 & 27.0 & 46.20 \\\\\nPretrained (gpt2-xl) & 38.0 & 52.0 & 46.0 & 61.0 & 75.0 & 25.5 & 35.0 & 47.49 \\\\\nDefault loss & 39.0$_{\\textcolor{forestgreen}{(+2.0)}}$ & 42.0$_{\\textcolor{forestgreen}{(+0.0)}}$ & 35.0$_{\\textcolor{forestgreen}{(+1.0)}}$ & 50.0$_{\\textcolor{forestgreen}{(+1.0)}}$ & 60.0$_{\\textcolor{forestgreen}{(+2.0)}}$ & 25.6$_{\\textcolor{forestgreen}{(+0.4)}}$ & 24.0$_{\\textcolor{forestgreen}{(+1.0)}}$ & 39.38$_{\\textcolor{forestgreen}{(+1.06)}}$ \\\\\ncovariance & 40.0$_{\\textcolor{forestgreen}{(+3.0)}}$ & 42.0$_{\\textcolor{forestgreen}{(+0.0)}}$ & 34.0$_{\\textcolor{forestgreen}{(+0.0)}}$ & 54.0$_{\\textcolor{forestgreen}{(+5.0)}}$ & 62.0$_{\\textcolor{forestgreen}{(+4.0)}}$ & 25.5$_{\\textcolor{forestgreen}{(+0.3)}}$ & 25.0$_{\\textcolor{forestgreen}{(+2.0)}}$ & 40.36$_{\\textcolor{forestgreen}{(+2.04)}}$ \\\\\nhinge & 40.0$_{\\textcolor{forestgreen}{(+3.0)}}$ & 42.0$_{\\textcolor{forestgreen}{(+0.0)}}$ & 37.0$_{\\textcolor{forestgreen}{(+3.0)}}$ & 57.0$_{\\textcolor{forestgreen}{(+8.0)}}$ & 62.0$_{\\textcolor{forestgreen}{(+4.0)}}$ & 25.6$_{\\textcolor{forestgreen}{(+0.4)}}$ & 24.0$_{\\textcolor{forestgreen}{(+1.0)}}$ & 41.08$_{\\textcolor{forestgreen}{(+2.76)}}$ \\\\\ninfonce\\_cosine & 40.0$_{\\textcolor{forestgreen}{(+3.0)}}$ & 42.0$_{\\textcolor{forestgreen}{(+0.0)}}$ & 33.0$_{\\textcolor{crimson}{(-1.0)}}$ & 53.0$_{\\textcolor{forestgreen}{(+4.0)}}$ & 61.0$_{\\textcolor{forestgreen}{(+3.0)}}$ & 25.7$_{\\textcolor{forestgreen}{(+0.5)}}$ & 27.0$_{\\textcolor{forestgreen}{(+4.0)}}$ & 40.24$_{\\textcolor{forestgreen}{(+1.92)}}$ \\\\\ninfonce\\_l2 & 41.0$_{\\textcolor{forestgreen}{(+4.0)}}$ & 42.0$_{\\textcolor{forestgreen}{(+0.0)}}$ & 35.0$_{\\textcolor{forestgreen}{(+1.0)}}$ & 55.0$_{\\textcolor{forestgreen}{(+6.0)}}$ & 60.0$_{\\textcolor{forestgreen}{(+2.0)}}$ & 24.9$_{\\textcolor{crimson}{(-0.3)}}$ & 27.0$_{\\textcolor{forestgreen}{(+4.0)}}$ & 40.70$_{\\textcolor{forestgreen}{(+2.38)}}$ \\\\\n\\bottomrule\n\\end{tabular}'